# Generated by Django 4.2 on 2024-02-08 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_client_owner_logs_owner_mailings_owner_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='frequency',
            field=models.CharField(choices=[('Ежедневно', 'Daily'), ('Еженедельно', 'Weekly'), ('Ежемесячно', 'Monthly')], default='Ежедневно', max_length=20, verbose_name='частота'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.CharField(choices=[('Выполнена', 'Completed'), ('Создана', 'Created'), ('В работе', 'Launched')], default='Создана', verbose_name='статус рассылки'),
        ),
    ]
