# Generated by Django 4.2 on 2024-02-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mailings_is_active_alter_mailings_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'permissions': [('set_active', 'может менять состояние активности')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
