# Generated by Django 4.2 on 2024-02-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mailings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mailings',
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(choices=[('Успешно', 'Successfully'), ('Неудачно', 'Failed'), ('Неизвестно', 'Unknown')], default='Неизвестно', verbose_name='статус'),
        ),
    ]
