# Generated by Django 4.2 on 2024-02-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_message_mailings_alter_logs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='cообщение'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.CharField(blank=True, choices=[('Выполнена', 'Completed'), ('Создана', 'Created'), ('В работе', 'Launched')], default='Создана', null=True, verbose_name='статус рассылки'),
        ),
    ]
