# Generated by Django 4.2 on 2024-02-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mailings_message_alter_mailings_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='message',
            new_name='message_title',
        ),
    ]
