# Generated by Django 4.2 on 2024-02-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_message_logs_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='message_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailings', verbose_name='сообщение'),
        ),
    ]
